Polimorphism
Schi8m-git/learning pull request #2
Opened 2021-04-02 08:33 UTC by Schi8m-git

2021-04-02 15:33 UTC, sov-87 requested changes

2021-04-02 15:33 UTC, sov-87 commented on lessons/polimorph/Polimorph.java
> +		printArray(arrayLength, arrayLength,intArray);
зачем методу что-то кроме массива передавать?

2021-04-03 10:29 UTC, Schi8m-git commented on lessons/polimorph/Polimorph.java
> +		printArray(arrayLength, arrayLength,intArray);
потому что длина массива каждый раз генерируется случайно, счетчик я включаю дважды. при одномерном массиве я могу дать условие i<=array.length. Однако когда задаю второй уровень массива, я не уаерен, что могу написать так эе и будет работать правильно. Поэтому я использовал переменную, описывающую длину и ширину массива и даю циклу условие через них.

2021-04-03 22:00 UTC, sov-87 commented on lessons/polimorph/Polimorph.java
> +		printArray(arrayLength, arrayLength,intArray);
массив себя всегда полностью описывает, у него всегда корректная длина.
когда массив состоит в свою очередь из массивов, то у каждого "вложенного" массива своя длина. и каждый "знает" про нее. поле length всегда содержит это значение

2021-04-09 16:57 UTC, closed without merging