Sin
Schi8m-git/learning pull request #7
Opened 2021-04-10 14:48 UTC by Schi8m-git

2021-04-11 18:51 UTC, sov-87 requested changes

2021-04-11 18:51 UTC, sov-87 commented on sin/Sin.java
> +	public static String getSinValue(double accuracy, int x, int i, int j, double factorial, double currentValue, double previousValue, double sum){
функция получения синуса должна принимать на вход только значение аргумента и точность.
также непонятно, почему она возвращает строку. значение синуса - вещественное число

2021-04-11 21:46 UTC, Schi8m-git commented on sin/Sin.java
> +	public static String getSinValue(double accuracy, int x, int i, int j, double factorial, double currentValue, double previousValue, double sum){
Это я так сократил код)

2021-04-11 22:41 UTC, sov-87 commented on sin/Sin.java
> +	public static double getSinValue(double accuracy, double x){
более четкая подсказка, чтобы убрать дублирование кода:
прочитать про явное приведение типов.

2021-04-19 07:24 UTC, sov-87 requested changes

2021-04-19 07:24 UTC, sov-87 commented on sin/Sin.java
> +			if (i/2*2 == i){
внутри условия должно быть только то, что зависит от условия. остальные вещи надо выносить.
здесь вообще удобнее тернарное на знак внутри выражения сделать

2021-04-19 07:24 UTC, sov-87 commented on sin/Sin.java
> +			double factorial = 1;
зачем тут задавать значение, если далее оно перетрется?

2021-04-19 07:24 UTC, sov-87 commented on sin/Sin.java
> +		for(double e = 1; e>=accuracy; e = Math.abs(currentValue-previousValue)){
циклы `for` лучше использовать для чего-то перечислимого. для подобных вещей лучше явно `while`

2021-04-21 19:08 UTC, Schi8m-git commented on sin/Sin.java
> +			double factorial = 1;
потому что i - это счетчик четности, а j - степени. Все это только ради правильного задания формулы синуса.

2021-04-21 19:28 UTC, sov-87 requested changes

2021-04-21 19:28 UTC, sov-87 commented on sin/Sin.java
> +			factorial = 1;
это вообще загадка. зачем в конце сбрасывать, если на следующей же итерации заново установишь значение?

2021-04-21 20:18 UTC, sov-87 requested changes

2021-04-21 20:18 UTC, sov-87 commented on sin/Sin.java
> +			sum = (i/2*2==i) ? (sum - (double)(Math.pow(x, j))/factorial) : (sum + (double)(Math.pow(x, j))/factorial);
здесь от тернарки только знак зависит, а не вся степень

2021-04-24 20:26 UTC, sov-87 requested changes

2021-04-24 20:26 UTC, sov-87 commented on sin/Sin.java
> +		sinCounter(accuracy, x);
лишний вызов

2021-04-24 20:26 UTC, sov-87 commented on sin/Sin.java
> +		double countResult = sinCounter(accuracy, x);
сохранять результат не обязательно

2021-04-24 20:40 UTC, merged